### ISSUE TITLE
run src/joy-dao.ts get error

### ISSUE THREAD

**Issue by Red-T007** [tea2x/nervos-dao-with-joyid#11]
In the line registerCustomLockScriptInfos(generateDefaultScriptInfos());, get error below, how to solve it?
```
Argument of type 'import("/Users/zh/Desktop/ckb-dao-sdk/node_modules/@ckb-ccc/lumos-patches/node_modules/@ckb-lumos/common-scripts/lib/common").LockScriptInfo[]' is not assignable to parameter of type 'import("/Users/zh/Desktop/ckb-dao-sdk/node_modules/@ckb-lumos/common-scripts/lib/common").LockScriptInfo[]'.
```

**Comment by Red-T007** [comment]
the problem come up at `joy-dao.ts` and `basic-wallet.ts`

**Comment by tea2x** [comment]
hello @brooke007 ,

The building process goes well on my end. 
What version of joyDAO are you working at? Or are you taking those files into your own project?

**Comment by tea2x** [comment]
https://www.npmjs.com/package/joy-dao

I built this npm package for building Nervos DAO transaction. 

here's example code:
https://github.com/tea2x/nervos-dao-with-joyid/blob/b150b66614ab3060c322f2410a8b96aefefd5ecc/src/App.tsx#L326

It might help you
